nmct.ssa.dropbox/Controllers/FilesController.cs
using nmct.ssa.dropbox.DataAccess;
using nmct.ssa.dropbox.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace nmct.ssa.dropbox.Controllers
{
    [Authorize]
    public class FilesController : Controller
    {
        // GET: Files
        public ActionResult Index()
        {
            bool isAdmin = User.IsInRole("Administrator");
            ViewBag.IsAdmin = isAdmin;
            ViewBag.MijnBestanden = DAFileRegistration.BestandenVanUser(User.Identity.Name);
            ViewBag.ToegangBestanden = DAFileRegistration.BestandenMetToegangVoor(User.Identity.Name, isAdmin);
            return View();
        }

        [HttpGet]
        public ActionResult Upload()
        {
            var context = new ApplicationDbContext();
            ViewBag.Users = context.Users;
            return View();
        }

        [HttpPost]
        public ActionResult Upload(HttpPostedFileBase file, string description, string[] wie)
        {
            if (file != null && file.ContentLength > 0)
            {
                var filename = Path.GetFileName(file.FileName);
                var path = Path.Combine(Server.MapPath("~/app_data/uploads"), filename);
                file.SaveAs(path);
                int fileId = DAFileRegistration.SaveFileRegistration(filename, description, User.Identity.Name);

                foreach(string user in wie)
                    DAFileRegistration.SaveDownloaders(user, fileId);
            }
            return RedirectToAction("Index");

        }

        [HttpGet]
        public ActionResult Download(int id)
        {
            FileRegistration reg = DAFileRegistration.GetFileRegistrationById(id);

            if (!User.IsInRole("Administrator") && User.Identity.Name != reg.UserName)
                return new HttpUnauthorizedResult();

            string path = Server.MapPath("~/app_data/uploads/");
            path += reg.FileName;
            DAFileLogging.SaveLog(id, User.Identity.Name);
            return File(System.IO.File.ReadAllBytes(path), System.Net.Mime.MediaTypeNames.Application.Octet, reg.FileName);
        }

        [Authorize]
        [HttpGet]
        public ActionResult ConfirmDelete(int id)
        {
            FileRegistration reg = DAFileRegistration.GetFileRegistrationById(id);
            if (reg == null) // not found
                return new HttpNotFoundResult();

            if (reg.UserName != User.Identity.Name) // not his own file, so can't delete it
                return new HttpUnauthorizedResult();

            ViewBag.FileRegistration = reg;
            return View();

        }

        [Authorize]
        [HttpGet]
        public ActionResult Delete(int id)
        {
            FileRegistration reg = DAFileRegistration.GetFileRegistrationById(id);
            if (reg == null) // not found
                return new HttpNotFoundResult();

            if (reg.UserName != User.Identity.Name) // not his own file, so can't delete it
                return new HttpUnauthorizedResult();

            string path = Server.MapPath("~/app_data/uploads/");
            path += reg.FileName;

            System.IO.File.Delete(path);

            DAFileRegistration.DeleteFile(id);

            return RedirectToAction("Index");
        }

        [HttpGet]
        [Authorize(Roles="Administrator")]
        public ActionResult Logs()
        {
            ViewBag.Logs = DAFileLogging.GetLogs();
            return View();
        }
    }
}

nmct.ssa.dropbox/Controllers/LogController.cs
using System.Collections.Generic;
using nmct.ssa.dropbox.DataAccess;
using nmct.ssa.dropbox.Models;
using System.Web.Http;
using nmct.ssa.dropbox.common;

namespace nmct.ssa.dropbox.Controllers
{
    
    public class LogController : ApiController
    {
        [Authorize]
        public IEnumerable<FileLog> Get()
        {
            return DAFileLogging.GetLogs();
        }
    }
}

nmct.ssa.dropbox/Views/Files/ConfirmDelete.cshtml
@using nmct.ssa.dropbox.Models;
@{
    ViewBag.Title = "ConfirmDelete";
    FileRegistration file = ViewBag.FileRegistration;
}

<h2>Echt verwijderen?</h2>
<p>Je staat op het punt om het volgende bestand te verwijderen.</p>

<table class="table">
    <tr>
        <th>#</th>
        <th>Naam</th>
        <th>Omschrijving</th>
        <th>Opgeladen op</th>
        <th>Gebruikersnaam</th>
    </tr>
    <tr>
        <td>@file.FileId</td>
        <td>@file.FileName</td>
        <td>@file.Description</td>
        <td>@file.UploadTime</td>
        <td>@file.UserName</td>
    </tr>
</table>

@Html.ActionLink("Verwijder", "Delete", "Files", new { id = @file.FileId }, new { @class = "btn btn-primary" })
@Html.ActionLink("Annuleer", "Index", "Files", new { @class = "btn btn-default" })

nmct.ssa.dropbox/Views/Files/Index.cshtml
@using nmct.ssa.dropbox.Models;
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@if(ViewBag.IsAdmin) { <p>Je bent ingelogd als administrator.</p> }

@Html.ActionLink("Nieuw bestand opladen", "Upload", "Files")

<h3>Mijn bestanden</h3>

<table class="table table-striped">
    <tr>
        <th>#</th>
        <th>Naam</th>
        <th>Omschrijving</th>
        <th>Opgeladen op</th>
        <th>Acties</th>
    </tr>
    @foreach (FileRegistration f in ViewBag.MijnBestanden)
    {
        <tr>
            <td>@f.FileId</td>
            <td>@f.FileName</td>
            <td>@f.Description</td>
            <td>@f.UploadTime</td>
            <td>
                @Html.ActionLink("Downloaden", "Download", "Files", new { id = f.FileId }, null) | 
                @Html.ActionLink("Verwijderen", "ConfirmDelete", "Files", new { id = f.FileId }, null)
            </td>
        </tr>
    }
</table>

<h3>Bestanden met mij gedeeld</h3>

<table class="table table-striped">
    <tr>
        <th>#</th>
        <th>Naam</th>
        <th>Omschrijving</th>
        <th>Opgeladen op</th>
        <th>Opgeladen door</th>
        <th>Acties</th>
    </tr>
    @foreach (FileRegistration f in ViewBag.ToegangBestanden)
    {
        <tr>
            <td>@f.FileId</td>
            <td>@f.FileName</td>
            <td>@f.Description</td>
            <td>@f.UploadTime</td>
            <td>@f.UserName</td>
            <td>
                @Html.ActionLink("Downloaden", "Download", "Files", new { id = f.FileId }, null) | 
                @Html.ActionLink("Verwijderen", "ConfirmDelete", "Files", new { id = f.FileId }, null)
            </td>
        </tr>
    }
</table>

nmct.ssa.dropbox/Views/Files/Logs.cshtml
@using nmct.ssa.dropbox.common;
@{
    ViewBag.Title = "Logs";
}

<h2>Logs</h2>

<table class="table table-striped">
    <tr>
        <th>#</th>
        <th>Gedownload door</th>
        <th>Gedownload op</th>
        <th>Bestandsid</th>
    </tr>
    @foreach (FileLog f in ViewBag.Logs)
    {
        <tr>
            <td>@f.Id</td>
            <td>@f.DownloadBy</td>
            <td>@f.TimeDownloaded</td>
            <td>@f.FileId</td>
        </tr>
    }
</table>

nmct.ssa.dropbox/Views/Files/Upload.cshtml
@{
    ViewBag.Title = "Upload";
}

<h2>Selecteer een bestand</h2>

@using (Html.BeginForm("Upload", "Files", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <h3>Omschrijving voor bestand:</h3>

    <textarea name="description"></textarea>
    
    <h3>Bestand:</h3>
    <input type="file" name="file"/>
    
    <h3>Wie mag dit bestand downloaden?</h3>
    <select name="wie" multiple>
        @foreach(nmct.ssa.dropbox.Models.ApplicationUser u in ViewBag.Users) {
            <option value="@u.UserName">@u.FirstName @u.Name</option>
        }
    </select>
    
    <button type="submit">Opladen</button>
}