nmct.ssa.dropbox/Controllers/ExternalUsersController.cs
using nmct.ssa.dropbox.common;
using nmct.ssa.dropbox.DataAccess;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace nmct.ssa.dropbox.Controllers
{
    public class ExternalUsersController : Controller
    {
        [HttpGet]
        [Authorize(Roles="Administrator")]
        public ActionResult Index()
        {
            return RedirectToAction("List");
        }
        
        public ActionResult List(){
            ViewBag.Models = DAExternalUser.GetExternalUsers();
            return View();
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            ExternalUser ext = DAExternalUser.GetById(id);
            return View(ext);
        }

        [HttpPost]
        public ActionResult Edit(ExternalUser ext)
        {
            DAExternalUser.Update(ext);
            return RedirectToAction("List");
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(ExternalUser ext)
        {
            DAExternalUser.New(ext);
            return RedirectToAction("List");
        }
    }
}

nmct.ssa.dropbox/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Dropbox</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("DropBox", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Files", "Index", "Files")</li>
                    <li>@Html.ActionLink("Upload", "Upload", "Files")</li>
                    @if (User.IsInRole("Administrator"))
                    {
                        <li>@Html.ActionLink("Logs", "Logs", "Files")</li>
                        <li>@Html.ActionLink("Externe gebruikers", "List", "ExternalUsers")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>